<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- "-windows" habilita as APIs do Windows (WinForms só roda no Windows). -->
	  <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IntegrationClient.WinForms</RootNamespace>
  </PropertyGroup>

</Project>
